### PR TITLE
Pygame mask

### PR DESCRIPTION
**Pull request by drnlm**
This implements pygame.mask

It passes pygame's test cases, as well as a number of extra test cases I've added to the tests to ensure correct behaviour (tavis doesn't show this correctly, since this branch predates our travis support).

I have tested this under python 2.7 and python 3.4

This addresses #15

### CODE REVIEW

**Comment by hodgestar** [comment]
Are the Travis build failures important?

**Comment by drnlm** [comment]
The travis push branch failures aren't important - this branch predates the .travis.yml file, so travis tries to use it's default config, which is very much the wrong thing here, leading to the unhelpful failure "The command "rake" exited with 1.".

The pr branch, which is using the right .travis.yml file. passes.

**Comment by hodgestar** [comment]
I've gone through everything except c9c35cb0d which I will try get to a bit later. Left a few minor comments, but generally looks good to me.

**Comment by hodgestar** [comment]
Left some minor comments on the commits and it looks like there is a debugging exit-at-50 check in the outline routine, but otherwise looks good.

**Comment by drnlm** [comment]
Ready for further review

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
